// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SlackYouTrack.CrossPlatform.Data;

#nullable disable

namespace SlackYouTrack.CrossPlatform.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("SlackYouTrack.CrossPlatform.Data.AttendanceEntity", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("AttendanceID");

                    b.Property<string>("Attended")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ClassID");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("StudentID");

                    b.Property<TimeSpan?>("TimeIn")
                        .HasColumnType("TEXT");

                    b.HasKey("AttendanceId");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.ToTable("Attendance", (string)null);

                    b.HasData(
                        new
                        {
                            AttendanceId = 1,
                            Attended = "Yes",
                            ClassId = 1,
                            StudentId = "DEMO-S-001",
                            TimeIn = new TimeSpan(0, 8, 57, 0, 0)
                        },
                        new
                        {
                            AttendanceId = 2,
                            Attended = "Yes",
                            ClassId = 1,
                            StudentId = "DEMO-S-002",
                            TimeIn = new TimeSpan(0, 9, 3, 0, 0)
                        },
                        new
                        {
                            AttendanceId = 3,
                            Attended = "No",
                            ClassId = 1,
                            StudentId = "DEMO-S-003"
                        });
                });

            modelBuilder.Entity("SlackYouTrack.CrossPlatform.Data.ClassEntity", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ClassID");

                    b.Property<DateTime>("ClassDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("ClassDate");

                    b.Property<string>("ClassRoom")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ClassRoom");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CourseID");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("EndTime");

                    b.Property<string>("InstructorId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("InstructorID");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("StartTime");

                    b.HasKey("ClassId");

                    b.HasIndex("ClassRoom");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Class", (string)null);

                    b.HasData(
                        new
                        {
                            ClassId = 1,
                            ClassDate = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClassRoom = "Demo Room A",
                            CourseId = "DEMO-C-001",
                            EndTime = new TimeSpan(0, 10, 0, 0, 0),
                            InstructorId = "DEMO-I-001",
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("SlackYouTrack.CrossPlatform.Data.CourseEntity", b =>
                {
                    b.Property<string>("CourseId")
                        .HasColumnType("TEXT")
                        .HasColumnName("CourseID");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstructorId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("InstructorID");

                    b.HasKey("CourseId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Course", (string)null);

                    b.HasData(
                        new
                        {
                            CourseId = "DEMO-C-001",
                            CourseName = "DEMO - Introduction to Attendance Tracking",
                            InstructorId = "DEMO-I-001"
                        });
                });

            modelBuilder.Entity("SlackYouTrack.CrossPlatform.Data.InstructorEntity", b =>
                {
                    b.Property<string>("InstructorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("InstructorID");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InstructorId");

                    b.ToTable("Instructor", (string)null);

                    b.HasData(
                        new
                        {
                            InstructorId = "DEMO-I-001",
                            FirstName = "Demo",
                            LastName = "Instructor"
                        });
                });

            modelBuilder.Entity("SlackYouTrack.CrossPlatform.Data.LocationEntity", b =>
                {
                    b.Property<string>("ClassRoom")
                        .HasColumnType("TEXT")
                        .HasColumnName("ClassRoom");

                    b.HasKey("ClassRoom");

                    b.ToTable("Location", (string)null);

                    b.HasData(
                        new
                        {
                            ClassRoom = "Demo Room A"
                        });
                });

            modelBuilder.Entity("SlackYouTrack.CrossPlatform.Data.RegisteredClassEntity", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("StudentID");

                    b.Property<string>("CourseId")
                        .HasColumnType("TEXT")
                        .HasColumnName("CourseID");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("RegisteredClasses", (string)null);

                    b.HasData(
                        new
                        {
                            StudentId = "DEMO-S-001",
                            CourseId = "DEMO-C-001"
                        },
                        new
                        {
                            StudentId = "DEMO-S-002",
                            CourseId = "DEMO-C-001"
                        },
                        new
                        {
                            StudentId = "DEMO-S-003",
                            CourseId = "DEMO-C-001"
                        });
                });

            modelBuilder.Entity("SlackYouTrack.CrossPlatform.Data.StudentEntity", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("StudentID");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.ToTable("Student", (string)null);

                    b.HasData(
                        new
                        {
                            StudentId = "DEMO-S-001",
                            FirstName = "Alex",
                            LastName = "Sample"
                        },
                        new
                        {
                            StudentId = "DEMO-S-002",
                            FirstName = "Jordan",
                            LastName = "Example"
                        },
                        new
                        {
                            StudentId = "DEMO-S-003",
                            FirstName = "Taylor",
                            LastName = "Demo"
                        });
                });

            modelBuilder.Entity("SlackYouTrack.CrossPlatform.Data.AttendanceEntity", b =>
                {
                    b.HasOne("SlackYouTrack.CrossPlatform.Data.ClassEntity", "Class")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SlackYouTrack.CrossPlatform.Data.StudentEntity", "Student")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SlackYouTrack.CrossPlatform.Data.ClassEntity", b =>
                {
                    b.HasOne("SlackYouTrack.CrossPlatform.Data.LocationEntity", "Location")
                        .WithMany("Classes")
                        .HasForeignKey("ClassRoom")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SlackYouTrack.CrossPlatform.Data.CourseEntity", "Course")
                        .WithMany("Classes")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SlackYouTrack.CrossPlatform.Data.InstructorEntity", "Instructor")
                        .WithMany("Classes")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("SlackYouTrack.CrossPlatform.Data.CourseEntity", b =>
                {
                    b.HasOne("SlackYouTrack.CrossPlatform.Data.InstructorEntity", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("SlackYouTrack.CrossPlatform.Data.RegisteredClassEntity", b =>
                {
                    b.HasOne("SlackYouTrack.CrossPlatform.Data.CourseEntity", "Course")
                        .WithMany("Registrations")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SlackYouTrack.CrossPlatform.Data.StudentEntity", "Student")
                        .WithMany("Registrations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SlackYouTrack.CrossPlatform.Data.ClassEntity", b =>
                {
                    b.Navigation("AttendanceRecords");
                });

            modelBuilder.Entity("SlackYouTrack.CrossPlatform.Data.CourseEntity", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("SlackYouTrack.CrossPlatform.Data.InstructorEntity", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Courses");
                });

            modelBuilder.Entity("SlackYouTrack.CrossPlatform.Data.LocationEntity", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("SlackYouTrack.CrossPlatform.Data.StudentEntity", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
